# TRANSFORMACIÓN DE DATOS

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from category_encoders import TargetEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import QuantileTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

In [2]:
ruta_proyecto = 'C:/Users/vifra/vidal cientifico de datos/Portafolio ML/Proyecto leadscoring/00_PROYECTO_LEADSCORING/'

In [3]:
nombre_cat = 'cat_resultado_eda.pickle'
nombre_num = 'num_resultado_eda.pickle'

In [10]:
#cat = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_cat)
#num = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_num)
cat = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_cat).reset_index()
num = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_num).reset_index()

Separar la target

In [12]:
num

,id,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,score_actividad,score_perfil
0,660737,0,0,0,0.00,15.0,15.0
1,660728,0,5,674,2.50,15.0,15.0
2,660727,1,2,1532,2.00,14.0,20.0
3,660719,0,1,305,1.00,13.0,17.0
4,660681,1,2,1428,1.00,15.0,18.0
...,...,...,...,...,...,...,...
5070,579564,1,8,1845,2.67,15.0,17.0
5071,579546,0,2,238,2.00,14.0,19.0
5072,579545,0,2,199,2.00,13.0,20.0
5073,579538,1,3,499,3.00,15.0,16.0
5074,579533,1,6,1279,3.00,15.0,18.0

In [35]:
target = num[['compra']].copy().reset_index(drop=True)

In [14]:
num.columns

Index(['id', 'compra', 'visitas_total', 'tiempo_en_site_total',
       'paginas_vistas_visita', 'score_actividad', 'score_perfil'],
      dtype='object')

In [15]:
cat.descarga_lm.value_counts()

descarga_lm
No     3161
Yes    1914
Name: count, dtype: int64

## TRANSFORMACIÓN DE CATEGÓRICAS

### One Hot Encoding

#### Variables a aplicar OHE

In [16]:
var_ohe = ['origen', 'fuente', 'ult_actividad', 'ambito', 'ocupacion',
       'descarga_lm']

#### Instanciar

In [17]:
ohe = OneHotEncoder(sparse = False, handle_unknown='ignore')

#### Entrenar y aplicar

In [18]:
cat_ohe = ohe.fit_transform(cat[var_ohe])

F:\cienciadedatos\envs\leadscoring\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

#### Guardar como dataframe

In [19]:
cat_ohe = pd.DataFrame(cat_ohe, columns = ohe.get_feature_names_out())

## UNIFICAR DATASETS TRANSFORMADOS

### Meter en una lista todos los dataframes generados

In [23]:
cat_ohe

,origen_API,origen_Landing Page Submission,origen_Lead Add Form,origen_OTROS,fuente_Chat,fuente_Direct Traffic,fuente_Google,fuente_OTROS,fuente_Organic Search,fuente_Reference,...,ambito_Operations Management,ambito_Select,ambito_Supply Chain Management,ambito_Travel and Tourism,ocupacion_OTROS,ocupacion_Student,ocupacion_Unemployed,ocupacion_Working Professional,descarga_lm_No,descarga_lm_Yes
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5070,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
5071,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5072,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5073,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
5074,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [24]:
df=pd.concat([cat_ohe,num],axis=1)

## REESCALAR VARIABLES

### Con Min-Max

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5075 entries, 0 to 5074
Data columns (total 44 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   origen_API                                5075 non-null   float64
 1   origen_Landing Page Submission            5075 non-null   float64
 2   origen_Lead Add Form                      5075 non-null   float64
 3   origen_OTROS                              5075 non-null   float64
 4   fuente_Chat                               5075 non-null   float64
 5   fuente_Direct Traffic                     5075 non-null   float64
 6   fuente_Google                             5075 non-null   float64
 7   fuente_OTROS                              5075 non-null   float64
 8   fuente_Organic Search                     5075 non-null   float64
 9   fuente_Reference                          5075 non-null   float64
 10  ult_actividad_Chat Conversation           5075 non-null   float64
 11  ult_actividad_Converted to Lead           5075 non-null   float64
 12  ult_actividad_Email Link Clicked          5075 non-null   float64
 13  ult_actividad_Email Opened                5075 non-null   float64
 14  ult_actividad_OTROS                       5075 non-null   float64
 15  ult_actividad_Page Visited on Website     5075 non-null   float64
 16  ult_actividad_SMS Sent                    5075 non-null   float64
 17  ambito_Banking, Investment And Insurance  5075 non-null   float64
 18  ambito_Business Administration            5075 non-null   float64
 19  ambito_Finance Management                 5075 non-null   float64
 20  ambito_Healthcare Management              5075 non-null   float64
 21  ambito_Human Resource Management          5075 non-null   float64
 22  ambito_IT Projects Management             5075 non-null   float64
 23  ambito_International Business             5075 non-null   float64
 24  ambito_Marketing Management               5075 non-null   float64
 25  ambito_Media and Advertising              5075 non-null   float64
 26  ambito_OTROS                              5075 non-null   float64
 27  ambito_Operations Management              5075 non-null   float64
 28  ambito_Select                             5075 non-null   float64
 29  ambito_Supply Chain Management            5075 non-null   float64
 30  ambito_Travel and Tourism                 5075 non-null   float64
 31  ocupacion_OTROS                           5075 non-null   float64
 32  ocupacion_Student                         5075 non-null   float64
 33  ocupacion_Unemployed                      5075 non-null   float64
 34  ocupacion_Working Professional            5075 non-null   float64
 35  descarga_lm_No                            5075 non-null   float64
 36  descarga_lm_Yes                           5075 non-null   float64
 37  id                                        5075 non-null   int64
 38  compra                                    5075 non-null   int64
 39  visitas_total                             5075 non-null   Int64
 40  tiempo_en_site_total                      5075 non-null   int64
 41  paginas_vistas_visita                     5075 non-null   float64
 42  score_actividad                           5075 non-null   float64
 43  score_perfil                              5075 non-null   float64
dtypes: Int64(1), float64(40), int64(3)
memory usage: 1.7 MB

#### Variables a reescalar con Min-Max

In [26]:
var_mms = df.iloc[:,39:].columns

#### Instanciar

In [27]:
mms = MinMaxScaler()

#### Entrenar y aplicar

In [28]:
df_mms = mms.fit_transform(df[var_mms])

#### Guardar como dataframe

In [29]:
#Añadir sufijos a los nombres
nombres_mms = [variable + '_mms' for variable in var_mms]

#Guardar como dataframe
df_mms = pd.DataFrame(df_mms,columns = nombres_mms)

## UNIFICAR DATASETS REESCALADOS

### Unir todos los dataframes

In [41]:
df_tablon = pd.concat([num.id,cat_ohe,df_mms,target],axis=1).set_index('id')

## GUARDAR DATASET TRAS TRANSFORMACIÓN DE DATOS

En formato pickle para no perder las modificaciones de metadatos.

In [42]:
#Definir los nombres del archivo
ruta_df_tablon = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'df_tablon.pickle'

In [43]:
#Guardar los archivos
df_tablon.to_pickle(ruta_df_tablon)